// Mocks generated by Mockito 5.0.16 from annotations
// in list_movie/test/features/films/usecases/get_film_common_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:list_movie/features/films/core/errors/search_exception.dart'
    as _i5;
import 'package:list_movie/features/films/domain/entities/response_film_entity.dart'
    as _i6;
import 'package:list_movie/features/films/domain/repositories/film_search_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [IFilmSearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIFilmSearchRepository extends _i1.Mock
    implements _i3.IFilmSearchRepository {
  MockIFilmSearchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.SearchException, _i6.ResponseFilmEntity>>
      getFilmsNowPlaying(int? page) => (super.noSuchMethod(
          Invocation.method(#getFilmsNowPlaying, [page]),
          returnValue: Future<
                  _i2.Either<_i5.SearchException, _i6.ResponseFilmEntity>>.value(
              _FakeEither_0<_i5.SearchException, _i6.ResponseFilmEntity>())) as _i4
          .Future<_i2.Either<_i5.SearchException, _i6.ResponseFilmEntity>>);
  @override
  _i4.Future<_i2.Either<_i5.SearchException, _i6.ResponseFilmEntity>>
      getFilmsCommon(int? page) => (super.noSuchMethod(
          Invocation.method(#getFilmsCommon, [page]),
          returnValue: Future<
                  _i2.Either<_i5.SearchException, _i6.ResponseFilmEntity>>.value(
              _FakeEither_0<_i5.SearchException, _i6.ResponseFilmEntity>())) as _i4
          .Future<_i2.Either<_i5.SearchException, _i6.ResponseFilmEntity>>);
  @override
  String toString() => super.toString();
}
